-- vim.cmd [[colorscheme neon]]
-- vim.cmd [[colorscheme tokyonight-moon]]
-- vim.cmd [[colorscheme nordfox]]
vim.cmd [[colorscheme nightfox]]
-- vim.cmd [[colorscheme catpuccin]]
-- vim.cmd [[colorscheme kanagawa]]
